import { createContext } from "react";

const subjectList = {
  "*": [],
  // 2021 ICT융합공학부
  y2_u4_g1: [
    // 2021 개편 소프트웨어 전공
    {
      id: "y2_u4_g1_m1",
      type: "basic",
      credit: 3,
      title: "가상현실콘텐츠기초",
      semester: 1,
    },
    {
      id: "y2_u4_g1_m1",
      type: "basic",
      credit: 3,
      title: "소프트웨어개론",
      semester: 1,
    },
    {
      id: "y2_u4_g1_m1",
      type: "basic",
      credit: 3,
      title: "전자공학개론및과학기술문서작성",
      semester: 1,
    },
    {
      id: "y2_u4_g1_m1",
      type: "basic",
      credit: 3,
      title: "C프로그래밍",
      semester: 2,
    },
    {
      id: "y2_u4_g1_m1",
      type: "basic",
      credit: 3,
      title: "파이썬응용",
      semester: 2,
    },
    {
      id: "y2_u4_g1_m1",
      type: "basic",
      credit: 3,
      title: "프로그래밍언어",
      semester: 2,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "디지털회로",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "이산수학",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "자료구조",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "자바프로그래밍",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "정보통신개론",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "객체지향프로그래밍",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "모바일프로그래밍",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "선형대수",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "임베디드기초",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "정보보호개론",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "통계응용",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "UNIX서버",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "기초암호학",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "알고리즘",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "웹프로그래밍",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "인공지능개론",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "자기주도프로젝트I",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "컴퓨터구조",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "기계학습",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "네트워크",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "데이터베이스",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "운영체제",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "자기주도프로젝트II",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "컴파일러구성론",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현대암호학",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "IoT응용",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "빅데이터",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "정보보호응용",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "캡스톤디자인(SW)I",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(단기)",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)I",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)II",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)III",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)IV",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "소프트웨어공학",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "정보보호관리및정책",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "캡스톤디자인(SW)II",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(단기)",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)I",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)II",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)III",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m1",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)IV",
      semester: 8,
    },

    // 2021 개편 가상현실 전공
    {
      id: "y2_u4_g1_m2",
      type: "basic",
      credit: 3,
      title: "가상현실콘텐츠기초",
      semester: 1,
    },
    {
      id: "y2_u4_g1_m2",
      type: "basic",
      credit: 3,
      title: "소프트웨어개론",
      semester: 1,
    },
    {
      id: "y2_u4_g1_m2",
      type: "basic",
      credit: 3,
      title: "전자공학개론및과학기술문서작성",
      semester: 1,
    },
    {
      id: "y2_u4_g1_m2",
      type: "basic",
      credit: 3,
      title: "C프로그래밍",
      semester: 2,
    },
    {
      id: "y2_u4_g1_m2",
      type: "basic",
      credit: 3,
      title: "파이썬응용",
      semester: 2,
    },
    {
      id: "y2_u4_g1_m2",
      type: "basic",
      credit: 3,
      title: "프로그래밍언어",
      semester: 2,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "게임엔진기초",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "메타버스프로그래밍",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "실감피지컬컴퓨팅",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "웹개발기초",
      semester: 3,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "3D모델링",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "가상현실프로그래밍",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "멀티미디어및실습",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "실감미디어컴퓨팅기초",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "웹개발응용",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "자료구조및알고리즘",
      semester: 4,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "디지털영상처리",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "실감디지털콘텐츠기획",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "웹서버프레임워크",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "윈도우즈프로그래밍",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "증강현실프로그래밍",
      semester: 5,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "XR UI/UX프로그래밍",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "게임프로그래밍",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "인터렉티브미디어개발",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "컴퓨터그래픽스",
      semester: 6,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "가상융합프로젝트I",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "디지털트윈프로그래밍",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "캡스톤디자인(VR)I",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "클라우드기반웹개발",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(단기)",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)II",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)III",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)IV",
      semester: 7,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "가상융합프로젝트II",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "캡스톤디자인(VR)II",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(단기)",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)I",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)II",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)III",
      semester: 8,
    },
    {
      id: "y2_u4_g1_m2",
      type: "choice",
      credit: 3,
      title: "현장실습(장기)IV",
      semester: 8,
    },
  ],
};
const SubjectContext = createContext({
  subjectState: subjectList,
});

export default SubjectContext;
